version: '3'

services:

  postgres-db:
    container_name: postgres-db-container-prod
    image: postgres:10.5
    expose:
      - 5432
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=eclassroom
    restart: unless-stopped

  jetty-server:
    container_name: jetty-api-server-prod
    build:
      context: ./rest
    image: jetty-api-server:latest
    expose:
      - 8080
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DB_PORT=5432
      - DB_NAME=eclassroom
      - DB_URL=postgres-db
      - DB_USER=root
      - DB_PASSWORD=root
      - UPLOAD_DIR=/var/lib/storage
    restart: unless-stopped
    depends_on:
      - postgres-db
    links:
      - postgres-db
    volumes:
      - ${HOST_UPLOAD_DIR}:/var/lib/storage

  nginx-server:
    container_name: nginx-server-container-prod
    build:
      context: ./web-client
    image: nginx-server:latest
    ports:
      - 4200:80
      - 8443:443
    restart: unless-stopped
    tty: true


volumes:
  postgres-db-volume:
  pgadmin4-volume:

